# Generated by Django 3.0.5 on 2020-04-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_simple_describe', models.CharField(max_length=200)),
                ('movie_detailed_describe', models.TextField()),
                ('movie_link', models.URLField()),
                ('movie_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
