# Generated by Django 3.0.3 on 2020-04-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200416_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
