# Generated by Django 3.0.5 on 2020-04-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invited_user_id',
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_username',
            field=models.CharField(default='not selected', max_length=100),
        ),
    ]
