# Generated by Django 3.0.5 on 2020-04-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20200410_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='inviter_user_id',
        ),
        migrations.AddField(
            model_name='invitation',
            name='inviter_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
