# Generated by Django 3.0.5 on 2020-04-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newgroupmanager',
            name='group',
        ),
        migrations.RemoveField(
            model_name='newgroupmanager',
            name='group_user',
        ),
        migrations.AddField(
            model_name='newgroupmanager',
            name='group_name',
            field=models.CharField(default='New Group', max_length=100),
        ),
        migrations.RemoveField(
            model_name='newgroupmanager',
            name='group_events',
        ),
        migrations.AddField(
            model_name='newgroupmanager',
            name='group_events',
            field=models.CharField(default='no events', max_length=100),
        ),
    ]
