# Generated by Django 3.0.5 on 2020-04-11 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wmt', '0011_auto_20200411_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupextend',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
