# Generated by Django 3.0.5 on 2020-04-15 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmt', '0015_auto_20200411_1154'),
        ('wmt', '0011_auto_20200412_1958'),
    ]

    operations = [
    ]
