# Generated by Django 3.0.5 on 2020-04-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmt', '0016_merge_20200414_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupextend',
            name='group_events',
        ),
    ]
