# Generated by Django 3.0.5 on 2020-04-15 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmt', '0017_remove_groupextend_group_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
