# Generated by Django 3.0.3 on 2020-04-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_review_link'),
        ('wmt', '0018_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movies.Movie'),
        ),
    ]
