# Generated by Django 3.0.3 on 2020-04-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmt', '0019_event_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.CharField(max_length=10),
        ),
    ]
