# Generated by Django 3.0.3 on 2020-04-16 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmt', '0020_auto_20200416_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='event time'),
        ),
    ]
