# Generated by Django 3.0.5 on 2020-04-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200416_1337'),
        ('wmt', '0022_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='event_votes', to='wmt.Vote'),
        ),
        migrations.AlterField(
            model_name='event',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='event_movies', to='movies.Movie'),
        ),
    ]
