# Generated by Django 3.0.5 on 2020-04-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_id', models.IntegerField()),
                ('inviter_user_id', models.IntegerField()),
                ('invited_user_id', models.IntegerField()),
            ],
        ),
    ]
