# Generated by Django 3.0.5 on 2020-04-05 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wmt', '0002_auto_20200405_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgroupmanager',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
